Make move more reliable, platform-independent.
In Fedora Toolbox-environment, key retrieval would fail due to a failure
to move the downloaded public key from the temporary location to the
PGP keys cache. By using the utility Files.move this action becomes more
reliable and is guaranteed to be platform-independent.

The produced stack traces were not too helpful.

java.io.IOException: Can't move file /tmp/-64362105801389810586520046351922325613pgp-public-key to /var/home/danny/dev/pgpverify-maven-plugin/target/it-repo/pgpkeys-cache/A6/AD/A6ADFC93EF34893E.asc
            at org.simplify4u.plugins.PGPKeysCache.receiveKey (PGPKeysCache.java:135)
            [...]